name: Deploy TypeScript App
on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm' # Enable npm caching

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci # Uses package-lock.json for exact versions

      # Step 4: Build the app
      - name: Build TypeScript app
        run: npm run build # Use your package.json build script

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Point to your dist directory
          exclude_assets: 'node_modules/**,.github/**'
